language: python
python:
    - "2.7"

sudo: required
cache:
    directories:
        - "~/.platformio"

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:samuel-bachmann/boost'
        packages:
        - libstdc++-7-dev
        - g++-7
        - boost1.60

before_install:
- sudo echo 'APT::Get::AllowUnauthenticated "true";' > /etc/apt/apt.conf.d/99myown

install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
- pip install -U platformio
- platformio update

script:
- platformio init
- platformio run --environment teensy36
- platformio run --environment teensy35
- platformio run --environment native
