language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - LD_LIBRARY_PATH="/home/travis/.platformio/packages/toolchain-linux-arm-cortexm4f-eabi/bin:/home/travis/.platformio/packages/toolchain-mac-arm-cortexm4f-eabi/bin"

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio init
    - platformio run --environment teensy36
    - platformio run --environment teensy35
