sudo: required
dist: bionic

language: python
python:
    - "3.7"

cache:
    directories:
        - "~/.platformio"

install:
    - sudo apt-get update -qq
    - sudo apt-get -y install g++ libboost-all-dev
    - pip install -U platformio

script:
    - platformio update
    - platformio init
    - platformio run --environment teensy36
    - platformio run --environment teensy35
    - platformio run --environment native
