language: python
python:
    - "2.7"

sudo: required
cache:
    directories:
        - "~/.platformio"

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:samuel-bachmann/boost'
        packages:
            - libstdc++-7-dev
            - g++-7
            - boost1.60

install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    - pip install -U platformio

script:
    - platformio update
    - platformio init
    - platformio run --environment teensy36
    - platformio run --environment teensy35
    - platformio run --environment native
