sudo: required
dist: focal

language: python
python:
    - "3.7"

cache:
    directories:
        - "~/.platformio"

install:
    - sudo apt-get -y install software-properties-common
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get -y install g++-9 libboost-all-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
    - pip install -U platformio

script:
    - platformio update
    - platformio init
    - platformio run --environment teensy41
    - platformio run --environment teensy40
    - platformio run --environment teensy36
    - platformio run --environment teensy35
    - platformio run --environment linux
