language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    - pip install -U platformio
    - platformio update

script:
    - platformio init
    - platformio run --environment teensy36
    - platformio run --environment teensy35
    - platformio run --environment native
