@startuml ctbot_config

namespace ctbot {
    class CtBotConfig {
        +{static} BLINK_TEST_AVAILABLE = false : constexpr bool
        +{static} ENA_TEST_AVAILABLE = false : constexpr bool
        +{static} LCD_TEST_AVAILABLE = false : constexpr bool
        +{static} LED_TEST_AVAILABLE = true : constexpr bool
        +{static} SENS_LCD_TEST_AVAILABLE = true : constexpr bool

        +{static} SWD_DEBUGGER_AVAILABLE = false : constexpr bool

        +{static} UART0_BAUDRATE = 4000000 : constexpr uint32_t
        +{static} UART5_PIN_RX = 34 : constexpr uint8_t
        +{static} UART5_PIN_TX = 33 : constexpr uint8_t
        +{static} UART5_BAUDRATE = 2000000 : constexpr uint32_t
        +{static} UART_FOR_CMD = 0 : constexpr uint8_t

        +{static} I2C0_PIN_SCL = 7 : constexpr uint8_t
        +{static} I2C0_PIN_SDA = 8 : constexpr uint8_t
        +{static} I2C2_PIN_SCL = 3 : constexpr uint8_t
        +{static} I2C2_PIN_SDA = 4 : constexpr uint8_t
        +{static} I2C3_PIN_SCL = 57 : constexpr uint8_t
        +{static} I2C3_PIN_SDA = 56 : constexpr uint8_t

        +{static} SHIFT_SDATA_PIN = 43 : constexpr uint8_t

        +{static} ENA_SCK_PIN = 41 : constexpr uint8_t
        +{static} ENA_RCK_PIN = 42 : constexpr uint8_t

        +{static} LED_SCK_PIN = 40 : constexpr uint8_t
        +{static} LED_RCK_PIN = 42 : constexpr uint8_t

        +{static} SHUTTER_PIN = 55 : constexpr uint8_t
        +{static} TRANSPORT_PIN = 24 : constexpr uint8_t
        +{static} ENC_L_PIN = 24 : constexpr uint8_t
        +{static} ENC_R_PIN = 25 : constexpr uint8_t
        +{static} RC5_PIN = 28 : constexpr uint8_t
        +{static} RC5_ADDR = 6 : constexpr uint8_t

        +{static} DISTANCE_L_PIN = 65 : constexpr uint8_t
        +{static} DISTANCE_R_PIN = 64 : constexpr uint8_t
        +{static} LINE_L_PIN = 18 : constexpr uint8_t
        +{static} LINE_R_PIN = 19 : constexpr uint8_t
        +{static} LDR_L_PIN = 37 : constexpr uint8_t
        +{static} LDR_R_PIN = 38 : constexpr uint8_t
        +{static} BORDER_L_PIN = 16 : constexpr uint8_t
        +{static} BORDER_R_PIN = 17 : constexpr uint8_t
        +{static} BAT_VOLTAGE_PIN = 39 : constexpr uint8_t

        +{static} MOT_L_PWM_PIN = 35 : constexpr uint8_t
        +{static} MOT_L_DIR_PIN = 29 : constexpr uint8_t
        +{static} MOT_R_PWM_PIN = 36 : constexpr uint8_t
        +{static} MOT_R_DIR_PIN = 30 : constexpr uint8_t
        +{static} MOT_PWM_MAX = 16000 : constexpr int16_t

        +{static} SERVO_1_PIN = 5 : constexpr uint8_t
        +{static} SERVO_2_PIN = 6 : constexpr uint8_t

        +{static} I2C_FOR_LCD = 2 : constexpr uint8_t

        +{static} SWD_CLOCK_PIN = 56 : constexpr uint8_t
        +{static} SWD_DATA_PIN = 57 : constexpr uint8_t
    }
}

@enduml
